### ISSUE TITLE
avoid removing of string when it's sole reference 

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnlib#126]
Hello :)

Any way to avoid this  : 
when i **remove** or **NOP** an LDSTR instruction from a method body and that the ldstr string was the only reference in all the file, dnlib removes that string when all i wanted was to remove the method byte's, not the string too

hope i'm clear sorry about wording :-S
regards

**Comment by 0xd4d** [comment]
It's because it doesn't include the old strings unless they're referenced from some ldstr instruction. If you remove them but plan on decrypting them at runtime or whatever you're going to have to force adding those strings (including other references the code uses, eg. member refs, method specs, etc). See `MetaData.USHeap` which is where code strings are stored.

There's also a `PreserveStringsOffsets` option but it keeps all old strings, perhaps not what you want.
