### ISSUE TITLE
ResolveMethod() Returning Completely Different Method

### ISSUE THREAD

**Issue by WeaponizedMeme** [0xd4d/dnlib#166]
I originally submitted this question to StackOverflow, and no one seemed to be able to solve it. Since this is somewhat related to dnlib, I decided to post it here, hoping someone could shed some insight on this:

When resolving methods from .NET DLLs, I noticed that the method being returned by Module.ResolveMethod() is completely different from original method. I am specifying the method's exact MetadataToken, so it makes absolutely no sense to me why I would end up with anything else but the original method.

In the below example, I have the 'Dispose()' method. I grab its metadata token and resolve it, only to find that I now have the 'OnBackColorChanged(System.EventArgs)'method

    static void Main(string[] args)
        {
            Assembly assembly = Assembly.LoadFrom(@"C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Windows.Forms.dll");
            MethodInfo method = assembly.GetModules()[0].GetTypes()[300].GetMethods()[362];
            Console.WriteLine(method); //Returns 'Void Dispose()'

            MethodInfo method2 = (MethodInfo)assembly.GetModules()[0].ResolveMethod(method.MetadataToken);
            Console.WriteLine(method2); //Returns 'Void OnBackColorChanged(System.EventArgs)' ...why?
        }

**Comment by UlyssesWu** [comment]
That's because a `MethodInfo.MetadataToken` needs to combine with `MethodInfo.Module` to identify a method. [MSDN: MethodInfo.MetadataToken](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.metadatatoken(v=vs.110).aspx#Syntax)

In your sample, the first `Dispose` method you got belongs to `System.Windows.Forms.Button`. That MetadataToken actually marks a `Dispose` method in `System.dll`. 

And the `OnBackColorChanged` method in `System.Windows.Forms.dll` just happens to have the same MetadataToken as that `Dispose` method in `System.dll`. But they are actually in different modules (and assemblies). 

You can get the MethodInfo for a method in another module because `System.Windows.Forms.Button` is inherited from `System.ComponentModel.Component`, and `System.Windows.Forms.Button` doesn't override the `Dispose` method in its base class.

I'm not an expert in Reflection and I just take a quick research in 15mins. Maybe 0xd4d can explain it better.

See also: [MSDN: MemberInfo.ReflectedType](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.reflectedtype(v=vs.110).aspx)

![dnspy-issue-metadatatoken](https://user-images.githubusercontent.com/4312781/37273364-88204624-2614-11e8-8d7f-378aea77fcdb.png)
