### ISSUE TITLE
dnlib vs cecil memory usage camparing

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#200]
I tried with PaintDotNet assemblies, What is your opinion?

**dnlib usage memory 133MB**
```
            var moduleContext = new ModuleContext();
			var asmResolver = new AssemblyResolver(moduleContext, true);
            var resolver = new Resolver(asmResolver);
			moduleContext.AssemblyResolver = asmResolver;
			moduleContext.Resolver = resolver;
		    ModuleDefMD moduleDefMd = ModuleDefMD.Load(@"D:\PaintDotNet.exe", moduleContext);

		    moduleDefMd.Write(@"D:\PaintDotNet_Save.exe");
```

**cecil usage memory 40MB**
```
		    ReaderParameters readerParameters = new ReaderParameters
		    {
		        AssemblyResolver = new CustomResolver()
		    };
		    ModuleDefinition moduleDef = ModuleDefinition.ReadModule(@"D:\PaintDotNet.exe", readerParameters);

		    moduleDef.Write(@"D:\PaintDotNet_Save.exe");
```

**Comment by UlyssesWu** [comment]
When I found dnlib, I never use cecil again because dnlib is more complete than cecil. That's it for me.

**Comment by bprg** [comment]
@UlyssesWu No doubt the dnlib is more complete, But it was a question to me why it consumes more than twice the memory?

**Comment by bprg** [comment]
I attached example cecil and dnlib,

> dnlib opens PDB files by default (that will use more memory), does cecil?
Maybe that's the reason, How to disable PDB reader?

> Did dnlib almost cause an OS crash when it allocated those 133MB?
Does not crash after save I've comparing memory task manager.

[Example.zip](https://github.com/0xd4d/dnlib/files/2093110/Example.zip)
Please download Paint.Net
https://www.dotpdn.com/files/paint.net.4.0.21.install.zip

**Comment by 0xd4d** [comment]
Looks like it's the mmapped IO. With it disabled (use File.ReadAllBytes()) and reading PDB files is disabled, process explorer says WS is 69K (dnlib) vs 52K (cecil). WIth mmapped IO enabled, dnlib's WS is 112K. The example is similar to yours except I made it more real-world by iterating over all types and members and reading method bodies.

The most important part of dnlib is that it can read obfuscated assemblies. That's the reason I wrote it. If it uses more memory and more CPU, then that's OK with me because it must be able to read real world assemblies, not only assemblies following the ECMA spec. Memory is very cheap.
