### ISSUE TITLE
How to edit Variable value

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#257]
I'd like to know how to modify local variables value and global variables value.

**Comment by 0xd4d** [comment]
You can find out how to do it by using your favorite compiler and then looking at the IL code.

**Comment by 0xd4d** [comment]
Seems like this isn't a problem anymore so closing it.

**Comment by Majx1337** [comment]
Hi, I'm trying to edit a specific string in an exe to another, the string is distinct and is not repeated anywhere in the program, I've accomplished the task by looping ModuleDef => TypeDef => MethodDef  as usual and it did the job, but I feel like there is another way to do it instead of looping. So is there any other way to accomplish the same thing?
