### ISSUE TITLE
Why does dnlib compare two MemberDef by name?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#450]
Why `a == b` is not enough?
![image](https://user-images.githubusercontent.com/2529999/149820674-3c8fc073-333f-454d-a18b-d0eb0fd85c3b.png)

```
class Program
{
    int a;
    int b;
}
```
Rename b to a by dnSpy, then SigCompare will think it's the same field, but it's not in fact.

**Comment by wtfsck** [comment]
It's useful when you open the same assembly but two different versions and need to compare defs. Reference equality is not what you want when comparing types `A` from both assemblies since they should be considered equal.

However it causes problems like you mentioned above.

This is a breaking change so we could change the default in v4 and add an option to use the old behavior if needed.

**Comment by wtfsck** [comment]
SigComparer could also be updated to check if they're in the same module and if so, use reference equality in that case.

**Comment by CreateAndInject** [comment]
@wtfsck This one should be marked as v4, it's important for dnSpy analyzer, since many obfuscator will generate duplicate names.

**Comment by wtfsck** [comment]
PRs welcome!
