### ISSUE TITLE
Align field data

### ISSUE THREAD

**Issue by wtfsck** [0xd4d/dnlib#454]
https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md#rules-for-il-rewriters

**Comment by ElektroKill** [comment]
If I understand this new specification correctly, the change should be as simple as modifying the following code:
https://github.com/0xd4d/dnlib/blob/e666538fd1ec733f0af8c57a3a96f5582ea704c0/src/DotNet/Writer/Metadata.cs#L2701-L2710
and introducing a change like this:
```csharp
uint rid = GetRid(field);

uint alignment = ModuleWriterBase.DEFAULT_CONSTANTS_ALIGNMENT;
if (field.FieldType is TypeDefOrRefSig tdrSig && tdrSig.TypeDef?.ClassLayout is {} classLayout)
	alignment = Math.Max(alignment, classLayout.PackingSize);

var iv = constants.Add(new ByteArrayChunk(ivBytes), alignment);
```
The spec mentions that the type of the field should be locally defined within the module meaning that we only have to check the `TypeDef` property of the `TypeDefOrRefSig` for the type. (Something to think about: technically a locally defined type can be referenced with a TypeRef, not sure how we should go about handling this (perhaps just always try to resolve the type?))

The use of `Math.Max` is there to eliminate the cases when the `PackingSize` field is 0 resulting in no alignment which follows the new specification as it mentions that in this case the `PackingSize` is the minimum alignment.

**Comment by wtfsck** [comment]
The `constants` field is added to `textSection` like so:

```C#
textSection.Add(constants, DEFAULT_CONSTANTS_ALIGNMENT)
```

so the constants can have max `DEFAULT_CONSTANTS_ALIGNMENT` alignment.

**Comment by ElektroKill** [comment]
Perhaps we could track the maximum alignment that a field needs in `ModuleWriterBase` when adding the FieldRVAs to `constants` chunk and then use this maximum alignment when adding `constants` to the `textSection`?

**Comment by wtfsck** [comment]
Yes, as long as it's a power of 2 and at least DEFAULT_CONSTANTS_ALIGNMENT and not a huge number we can use that instead of the default value.

**Comment by ElektroKill** [comment]
After further inspection, the current order of execution of the code is not necessarily compatible with the approach I outlined in my previous comment.

`textSection.Add(constants, DEFAULT_CONSTANTS_ALIGNMENT)` is executed before `Metadata` has a chance to do any of the row and table creation meaning that the FieldRVA rows are initialized after the `constants` chunk (which is just a list of other chunks) has been added to the `textSection` with DEFAULT_CONSTANTS_ALIGNMENT.

This means that the approach to store the calculated alignment in a field in `Metadata` and then using it when adding the `constants` chunk will not work unless significant changes are done to the writer to reorder the steps (if possible). I'm not really comfortable with doing such big changes to the writer so I won't be contributing a resolution to this issue for now.

**Comment by wtfsck** [comment]
Max alignment should only be needed when writing the sections so we should be able to update the section's alignment before we write the sections.

**Comment by ElektroKill** [comment]
The simplest solution I could come up with as of now is to make a modification to the `ChunkList<T>` or `ChunkListBase<T>` class to allow modifying the alignment of a chunk added to them. The `constants` chunk is added to the `textSection` field of type `PESection` which inherits from `ChunkList<T>`.

This would allow the writer to keep the current order of events by first adding the `constants` chunk to the `textSection` with the default alignment and then later updating the alignment field when the new alignment has been computed but before the offsets of the data are calculated.

This approach would be rather simple from the implementation side but it has some noticeable drawbacks for API consumers. There are scenarios (especially obfuscators) that move the `constants` chunk to a different section in order to apply some sort of encryption to it (ConfuserEx is an example of this with its AntiTamper protection). Doing this usually means removing the chunk from the `textSection` using the `Remove` method which returns the alignment of the chunk. The change would mean that the call to `Remove` could return a different alignment depending on when in the writing process it is called making it confusing for developers which alignment is valid and would make the time when the moving operation is performed more complicated.

I'm still not sure how this should be implemented in a proper way that doesn't make the processing of tampering with the constants chunk more confusing to the end user.

> Max alignment should only be needed when writing the sections so we should be able to update the section's alignment before we write the sections.

I'm not exactly sure what you mean here in terms of implementation, the sections in dnlib do not store their alignment as they are implemented as a list of chunks. The alignment of each chunk making up the section is calculated here:
https://github.com/0xd4d/dnlib/blob/b8cf2bf67799a4f3bec26aa62d8c4986a909b49a/src/DotNet/Writer/ChunkListBase.cs#L72
and the only way to update the alignment of the `constants` chunk if it was already added would be to update the entry for it in the list unless I am missing something here.

**Comment by wtfsck** [comment]
Yes it looks like this will be very simple, unless you can find a problem with this impl. Also since it's generic (no hard coded `constants` ref) it shouldn't be a problem if some obfuscator moves `constants` to some other section.

We could add a new `IChunk` method:

```C#
// We could return 0 to mean 'use default alignment'
// eg. ChunkListBase<T>:
override uint CalculateAlignment() {
	// Since it doesn't know its own default alignment, use 0
	uint alignment = 0;
	foreach (var elem in chunks) {
		// This is read only, we can just create a new struct and store it in chunks
		elem.alignment = max(elem.alignment, elem.chunk.CalculateAlignment());
		alignment = max(alignment, elem.alignment);
	}
	return alignment;
}
```

We can just call `sections.CalculateAlignment()` before we call `SetOffset()` (eg. in `CalculateRvasAndFileOffsets()`)

Once all constants have different alignments, we could also optimize the constants section by sorting all elements by alignment (eg. from high to low value). `UniqueChunkList<T>` could do that in its own `CalculateAlignment()` override (that calls the base impl) and then sorts the list before returning. That could save a few bytes if there's a lot of padding between different constants.

**Comment by ElektroKill** [comment]
Hi,

Sorry for the delay. I was on a week-long holiday. I took a look at implementing the solution you proposed and I have some questions. Adding a `CalculateAlignment` to `IChunk` makes a lot of sense. I went ahead and did so and implemented it in `ChunkListBase<T>` in a similar way to what you proposed (had to get rid of readonly issue by creating a new `Elem` and overwriting it in the list). 

However, I am running into a bit of a dilemma. I'm not really sure what the `CalculateAlignment` method should return for other types of chunks, for example, `ImportDirectory`, `RelocDirectory`, `MethodBody`, `HeapBase`, etc. as some of these are not really added to any `ChunkListBase<T>`. I also assume that for such an implementation we'd need to extend `ByteArrayChunk` to allow settings custom alignment which will be used when adding to the chunk list. Though it would make it quite confusing that this alignment is only respected when adding to `ChunkListBase<T>`. This would have to be made clear to the user or some additional changes would need to be made to respect the alignment returned by the call when calculating all the offsets (though this raises additional concerns for the current implementation of `CalculateAlignment` for `ChunkListBase<T>` as we don't really want to align the whole list to the maximum alignment of all chunks).

I'm also wondering whether adding the call to `CalculateAlignment` into `ModuleWriterBase.CalculateRvasAndFileOffsets` right before `chunk.SetOffset` is called is the eight move here or not.

**Comment by wtfsck** [comment]
> ImportDirectory, RelocDirectory

They're added to a TextSection and can use the default alignment so should return 0.

> MethodBody, HeapBase

These can also return 0 since metadata writer knows what alignments they should have.

> I also assume that for such an implementation we'd need to extend ByteArrayChunk to allow settings custom alignment which will be used when adding to the chunk list.

Yes it could take an optional argument with the expected alignment (arg should default to 0 = use default alignment).

> This would have to be made clear to the user or some additional changes would need to be made to respect the alignment returned by the call when calculating all the offsets

Yes there's probably some code that uses a ByteArrayChunk/IChunk that don't want to use the provided alignment and take care of that by themselves (or at least require that the alignment is <= the alignment they expect). They could verify that the return value is valid and throw if not.

> though this raises additional concerns for the current implementation of CalculateAlignment for ChunkListBase<T> as we don't really want to align the whole list to the maximum alignment of all chunks

Why wouldn't we? If we have 3 chunks with required alignments 2, 8 and 4, then the alignment of the parent must be 8. If no order is required, we can sort this eg. <chunk with 8-byte alignment><chunk with 4-byte alignment><chunk with 2-byte alignment>.

> I'm also wondering whether adding the call to CalculateAlignment into ModuleWriterBase.CalculateRvasAndFileOffsets right before chunk.SetOffset is called is the eight move here or not.

It needs to be called before we start writing it and figuring out offsets/rvas and that method is always called before that happens.
