### ISSUE TITLE
HasOverrides Generic Type

### ISSUE THREAD

**Issue by workgroupengineering** [0xd4d/dnlib#523]
Considering following code:

```c#
public class MyList:List<string>
{
   public override void Add(string name)
   {
        //do ... 
   }
}
``` 

when I enumerate the methods of MyList, the Add method has HasOverrides equal to false and Overrides is empty.

I would have expected HasOverrides to be True and Overrides to contain IList.Add<T>

What is the correct behavior?

**Comment by wtfsck** [comment]
There's no reason for the compiler to add any override since the name matches the overloaded method. Try implementing an interface and use explicit interface implementation https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation.

See the ECMA spec.

**Comment by workgroupengineering** [comment]
Thanks for the reply,
You are right, I made the wrong example.

The correct example is this:

```csharp
public class MyClass : ObservableCollection<string> {
	protected override void InsertItem(int index, string item) 
        {
          // Do ....
          base.InsertItem(index, item);
        }
}
```
