### ISSUE TITLE
TableStream question

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnlib#72]
http://image.prntscr.com/image/c0de58fa4a33421a999fec35d7b55f70.png
How I can get this name with dnlib?

I tried with this:
var test = module.MetaData.TablesStyeam.FileTable.Columns[0(for example)].Name;

but returns the members name :(

Thanks.

**Comment by 0xd4d** [comment]
![pic1](https://cloud.githubusercontent.com/assets/1060731/17899905/46b84a9e-695d-11e6-9111-b0a5d2bd233b.png)

As you can see, it's a `#Strings` offset. You have to get the offset then use the `#Strings` heap to get the string.

Why are you even using the low-level metadata API? It's more difficult to use since you have to have knowledge of .NET metadata tables.

BTW, instead of posting links to pics, you can just drag and drop them here and github will show them inline, like my picture above. Just a tip. ;)

**Comment by CodeShark-Dev** [comment]
I made this code and works fine for me. Thanks so much :+1: 
`static bool IsPacked(ModuleDefMD module) {
            var files = module.MetaData.TablesStream.FileTable.Columns;

            var ok = false;
            foreach (var file in files) {
                if (file.ColumnSize != ColumnSize.Strings)
                    continue;

                var stringStream = module.MetaData.StringsStream;
                var fileName = stringStream.Read((uint)file.Index);
                if (fileName == ModuleName)
                    ok = true;
            }

            return ok;
        }`

**Comment by 0xd4d** [comment]
BTW, the `Name` column is column `#2` (i.e., index `1`). Your code above uses `file.Index` which is just the index of the column, or `1`. Perhaps it happens to be the offset of the name you're looking for but that's just coincidence.

Try something like:

```C#
			for (uint rid = 1; rid < module.MetaData.TablesStream.FileTable.Rows; rid++) {
				var row = module.TablesStream.ReadFileRow(rid);
				var name = module.StringsStream.ReadNoNull(row.Name);
				if (name == "XXXXXXXXX") {
					//...
				}
			}
```
