### ISSUE TITLE
[Question] Is possible get the bytes of an instruction?

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnlib#80]

**Comment by 0xd4d** [comment]
If it's an instruction without a metadata token or a string token, then it's easy. Otherwise you'll have to get the bytes from an existing assembly by reading the method body. The instruction contains the offset, and the method has an RVA, and its body has a HeaderSize, add those together and you get the address of the instruction. Instruction.GetSize() returns the size of the instruction.

**Comment by CodeShark-Dev** [comment]
Wow, thanks alot 👍

**Comment by bprg** [comment]
I din't notice, I want access _strings token_ can you please more explain about this?

**Comment by 0xd4d** [comment]
The only way is to parse the method body yourself, see `dnlib.DotNet.Emit.MethodBodyReaderBase` and a class deriving from it: `dnlib.DotNet.Emit.MethodBodyReader`
