### ISSUE TITLE
Incorrect IsCorlib in CoreCLR

### ISSUE THREAD

**Issue by yck1509** [0xd4d/dnlib#82]
CoreCLR uses something called 'facade' to modularize core types. All primitive types are now in another assembly 'System.Private.CoreLib' and they're forwarded from mscorlib. This breaks IsCorlib() and other methods.

I can't think of a good way to fix IsCorlib, except adding that name to the list of system libraries. However due to the fact that it is possible to forward primitive types from mscorlib, there might be other runtimes that decided to do the same, but with some other target assembly names.

Sample code:
```C#
			var resolver = new AssemblyResolver();
			resolver.PreSearchPaths.Add(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0");
			var ctx = new ModuleContext(resolver);
			var m = ModuleDefMD.Load(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\mscorlib.dll", ctx);
			var t = m.CorLibTypes.Int32.ToTypeDefOrRef().ResolveTypeDefThrow();
			// Output value: false; Expected value: true
			Console.WriteLine(t.IsPrimitive);
```

**Comment by 0xd4d** [comment]
I've added a commit (54a47c13f9da0a1841c9196ffbd15ca68879045e). It now checks for System.Object and if found it assumes it's the core library. There's also a check in IsCorLib for `System.Private.CoreLib` since CoreCLR is used a lot. There should be no references to the private core library, but if there is a ref to it, the only way to know for sure whether it's a core library would be to resolve it (assuming it uses a new corlib name).

**Comment by yck1509** [comment]
The fix seems good enough for IsCorLib. Even so, for other methods the use IsCorLib (e.g. TypeDef.IsPrimitive), it would fail if someone (who is crazy enough) moves the primitive types into separate assemblies. I suppose a better fix would be checking whether `mscorlib` exports that type. However it seems expensive to check that information so I'll be happy to set IsCoreLibraryModule manually.

**Comment by 0xd4d** [comment]
Not sure if it would be allowed to move them to separate assemblies, i.e., all primitive types and 'core' types (eg. int, string, object) should be in the same assembly. I also see no advantage in moving these core types into separate assemblies. I think Roslyn assumes all core types are in the same assembly, so that would break some compilers.

**Comment by yck1509** [comment]
I'm sure there is no hard limit on which assemblies primitive types reside in, as long as there there are TypeForwardedToAttributes in `mscorlib`, because the binder respects the forwarding directive even when loading primitive types (check `MscorlibBinder::LoadPrimitiveType`@binder.cpp for details).

For commonly available runtime there would not be no advantages to do it. However for some hypothetical extreme modular runtime, it might make sense to separate the types into modules (e.g. reflection stuff into a module, custom attribute stuff into another module) to reduce binary size. Also the CLI spec seems to permit omission floating point types.

Also the type forwarding is entirely done in runtime. I don't think it would affect Roslyn as the assembly reference is still points to `mscorlib`

**Comment by 0xd4d** [comment]
Yes, splitting up types into separate assemblies for PERF / maintenance reasons is one reason, but I doubt anyone in their right mind would move the core types (int, object, string, I'm not talking about List<T> etc) to separate assemblies. I can only think of one reason to move System.Object to assembly A and System.Int32 to assembly B: to prove that it's possible.
